### ISSUE TITLE
Improve the aesthetics of this component

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/KeyVaultModule#11]
![image](https://user-images.githubusercontent.com/9479367/47600565-6029c380-d9c3-11e8-8ad9-2b8cb1294e15.png)

**Comment by Luis-Fernando-Molina** [comment]
![image](https://user-images.githubusercontent.com/9479367/47600577-a4b55f00-d9c3-11e8-8a74-18f065a3e2eb.png)

- 1 inside 2 doesnt look well
- 3) an orange button "New Key" would be easier to understand in this context
- 4) I guess this message is an ELSE of a list with no item. The user arriving here does not know up there a list will be, so there is no need to tell him that currently there are not items. Just nothing would be better in this case.
-5) If there are no items, "Create ANOTHER key" does not make sense. Remove the text and just leave the botton with "New Key" alone

**Comment by Luis-Fernando-Molina** [comment]
Other improvements:

- remove the panel 1
- put the panel 2 with the same style used in the following picture

![image](https://user-images.githubusercontent.com/9479367/47600622-c531e900-d9c4-11e8-85da-74f10936bdc9.png)

- Add the following Title: "Add a new exchange key to your Key Vault"
- Add the following Paragraph: "Use this form to add a new key that will allow your bots to access your account at an Exchange. First you need to generate the key at your Exchange Platform. For help on how to do that, please check the instructions here" (link to the instructions on the documentation)

**Comment by matbenitez** [comment]
Completed
