### ISSUE TITLE
New Item on NavBar> Add Key

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/KeyVaultModule#13]
Insert a new Item on the Nav Bar :  Add Key, with a PLUS icon or similar.

![image](https://user-images.githubusercontent.com/9479367/47600789-f7dce100-d9c6-11e8-8039-bd0104996633.png)

This should show the component in charge of adding a key.

**Comment by matbenitez** [comment]
For simplicity of navigation, it was decided to leave the manage functionality in one place. This can be changed when we decide to unify the look and feel of the actions across modules.

**Comment by matbenitez** [comment]
Completed
