### ISSUE TITLE
Form out of modal to normal screen

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/KeyVaultModule#14]
Move this form outside this modal to the sheet outlined in https://github.com/AdvancedAlgos/KeyVaultModule/issues/11

![image](https://user-images.githubusercontent.com/9479367/47600753-6ff6d700-d9c6-11e8-9c78-02131b38f6c1.png)

**Comment by matbenitez** [comment]
Completed
